project:
  type: website

website:
  title: ""
  favicon: assets/favicon.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Projects"
        href: projects.qmd
      - text: "My Thoughts"
        href: blogs.qmd
      - text: "More"
        menu:
          - text: "Resume"
            href: resume.qmd
          - text: "Who Am I?"
            href: my-story.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yjhouma/
      - icon: github
        href: https://github.com/yjhouma
      - icon: spotify
        href: https://open.spotify.com/artist/61pEtv6jEM12tiHXu9e04Y
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


jupyter:
  kernelspec:
    name: forecasting
    language: python
    display_name: Forecasting Environment
  conda:
    path: /opt/homebrew/Caskroom/miniforge/base/bin/conda
  python: /opt/homebrew/Caskroom/miniforge/base/envs/forecasting/bin/python