<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yohanes Jhouma Parulian N">
<meta name="dcterms.date" content="2024-06-15">

<title>Creating a Content-based Recommender System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Data Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blogs.html"> 
<span class="menu-text">My Thoughts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../../resume.html">
 <span class="dropdown-text">Resume</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../my-story.html">
 <span class="dropdown-text">Who Am I?</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/yjhouma/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/yjhouma"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://open.spotify.com/artist/61pEtv6jEM12tiHXu9e04Y"> <i class="bi bi-spotify" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Creating a Content-based Recommender System</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Yohanes Jhouma Parulian N </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 15, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#libraries-for-this-project" id="toc-libraries-for-this-project" class="nav-link active" data-scroll-target="#libraries-for-this-project">Libraries for this project</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a>
  <ul class="collapse">
  <li><a href="#structure-of-the-dataset" id="toc-structure-of-the-dataset" class="nav-link" data-scroll-target="#structure-of-the-dataset">Structure of the Dataset</a>
  <ul class="collapse">
  <li><a href="#movies-metadata" id="toc-movies-metadata" class="nav-link" data-scroll-target="#movies-metadata">Movies Metadata</a></li>
  <li><a href="#movies-credit" id="toc-movies-credit" class="nav-link" data-scroll-target="#movies-credit">Movies Credit</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data Preprocessing</a>
  <ul class="collapse">
  <li><a href="#combining-both-tables" id="toc-combining-both-tables" class="nav-link" data-scroll-target="#combining-both-tables">Combining both tables</a></li>
  <li><a href="#handling-missing-value" id="toc-handling-missing-value" class="nav-link" data-scroll-target="#handling-missing-value">Handling missing value</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#exploring-genre" id="toc-exploring-genre" class="nav-link" data-scroll-target="#exploring-genre">Exploring Genre</a>
  <ul class="collapse">
  <li><a href="#how-many-genre-a-movie-have" id="toc-how-many-genre-a-movie-have" class="nav-link" data-scroll-target="#how-many-genre-a-movie-have">How many Genre a movie have?</a></li>
  <li><a href="#genre-distribution" id="toc-genre-distribution" class="nav-link" data-scroll-target="#genre-distribution">Genre Distribution</a></li>
  </ul></li>
  <li><a href="#exploring-keywords" id="toc-exploring-keywords" class="nav-link" data-scroll-target="#exploring-keywords">Exploring Keywords</a>
  <ul class="collapse">
  <li><a href="#numbers-of-keywords-in-a-movie" id="toc-numbers-of-keywords-in-a-movie" class="nav-link" data-scroll-target="#numbers-of-keywords-in-a-movie">Numbers of Keywords in a movie</a></li>
  </ul></li>
  <li><a href="#how-many-keywords-there-are" id="toc-how-many-keywords-there-are" class="nav-link" data-scroll-target="#how-many-keywords-there-are">How many keywords there are</a></li>
  <li><a href="#exploring-overviewthe-plot-description" id="toc-exploring-overviewthe-plot-description" class="nav-link" data-scroll-target="#exploring-overviewthe-plot-description">Exploring Overview/The plot description</a>
  <ul class="collapse">
  <li><a href="#how-many-words-contained-in-an-overview" id="toc-how-many-words-contained-in-an-overview" class="nav-link" data-scroll-target="#how-many-words-contained-in-an-overview">How many words contained in an overview?</a></li>
  </ul></li>
  <li><a href="#exploring-director" id="toc-exploring-director" class="nav-link" data-scroll-target="#exploring-director">Exploring Director</a>
  <ul class="collapse">
  <li><a href="#extracting-director-from-the-crew" id="toc-extracting-director-from-the-crew" class="nav-link" data-scroll-target="#extracting-director-from-the-crew">Extracting Director from the Crew</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a>
  <ul class="collapse">
  <li><a href="#considering-ranking-and-scoring" id="toc-considering-ranking-and-scoring" class="nav-link" data-scroll-target="#considering-ranking-and-scoring">Considering Ranking and Scoring</a></li>
  <li><a href="#genres" id="toc-genres" class="nav-link" data-scroll-target="#genres">Genres</a></li>
  <li><a href="#keywords" id="toc-keywords" class="nav-link" data-scroll-target="#keywords">Keywords</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#director" id="toc-director" class="nav-link" data-scroll-target="#director">Director</a></li>
  <li><a href="#putting-it-together" id="toc-putting-it-together" class="nav-link" data-scroll-target="#putting-it-together">Putting it Together</a>
  <ul class="collapse">
  <li><a href="#creating-pipeline-for-feature-extraction" id="toc-creating-pipeline-for-feature-extraction" class="nav-link" data-scroll-target="#creating-pipeline-for-feature-extraction">Creating Pipeline for Feature Extraction</a></li>
  <li><a href="#joining-all-feature" id="toc-joining-all-feature" class="nav-link" data-scroll-target="#joining-all-feature">Joining all feature</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#build-a-recommender-system" id="toc-build-a-recommender-system" class="nav-link" data-scroll-target="#build-a-recommender-system">Build a Recommender System</a>
  <ul class="collapse">
  <li><a href="#running-the-recommender-function" id="toc-running-the-recommender-function" class="nav-link" data-scroll-target="#running-the-recommender-function">Running the Recommender Function</a></li>
  </ul></li>
  <li><a href="#improving-recomender-system" id="toc-improving-recomender-system" class="nav-link" data-scroll-target="#improving-recomender-system">Improving Recomender System</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="libraries-for-this-project" class="level1">
<h1>Libraries for this project</h1>
<div id="016c31a7" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics.pairwise <span class="im">import</span> cosine_similarity</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Have you ever had a friend ask you to recommend a movie or song based on something they just watched or listened to? It’s pretty common, right? You think about what they might like, considering their taste, and suggest something similar. That’s basically what a recommender system does, but with a lot more data and a bit more sophistication.</p>
<p>Recommender systems are like your personal assistant, suggesting things you might like based on your preferences and behavior. They’re everywhere: Netflix suggests movies, Spotify recommends songs, and Amazon points you to products you might want to buy.</p>
<p>In general, there are three types od recommender systems:</p>
<ol type="1">
<li><p><strong>Content-Based</strong>. Imagine you just watched a movie with your favorite genre. A content-based system would suggest other movies with similar genres and plot.</p></li>
<li><p><strong>Collaborative Filtering</strong>. Think of Netflix or Spotify, where you get recommendations based on what other users with similar tastes liked.</p></li>
<li><p><strong>Hybrid</strong>. Like the name suggests, this recommender system combine both content-based and colaborative filtering to give a more accurate suggestions.</p></li>
</ol>
<p>In this project, we’re building a content-based recommender system using the TMDB 5000 dataset. We’ll create a system that can suggest movies based on their content.</p>
</section>
<section id="dataset" class="level1">
<h1>Dataset</h1>
<p>For this project, we’re using the TMDB 5000 dataset, which is a collection of movie information gathered from <a href="https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata">The Movie Database (TMDB)</a>. This dataset provides a wealth of details about movies, including metadata like titles, genres, plot summaries, cast and crew, release dates, and user ratings.</p>
<section id="structure-of-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="structure-of-the-dataset">Structure of the Dataset</h2>
<p>The TMDB 5000 dataset consists of two main files:</p>
<ol type="1">
<li><strong>movies_metadata.csv</strong>: Contains metadata for each movie, including title, genres, overview, release date, and more.</li>
<li><strong>credits.csv</strong>: Contains information about the cast and crew for each movie.</li>
</ol>
<section id="movies-metadata" class="level3">
<h3 class="anchored" data-anchor-id="movies-metadata">Movies Metadata</h3>
<div id="a4920dbf" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>movies_metadata_df <span class="op">=</span> pd.read_csv(<span class="st">'data/tmdb_5000_movies.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>movies_metadata_df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>(4803, 20)</code></pre>
</div>
</div>
<div id="5f0eeea1" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>movies_metadata_df.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">budget</th>
<th data-quarto-table-cell-role="th">genres</th>
<th data-quarto-table-cell-role="th">homepage</th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">keywords</th>
<th data-quarto-table-cell-role="th">original_language</th>
<th data-quarto-table-cell-role="th">original_title</th>
<th data-quarto-table-cell-role="th">overview</th>
<th data-quarto-table-cell-role="th">popularity</th>
<th data-quarto-table-cell-role="th">production_companies</th>
<th data-quarto-table-cell-role="th">production_countries</th>
<th data-quarto-table-cell-role="th">release_date</th>
<th data-quarto-table-cell-role="th">revenue</th>
<th data-quarto-table-cell-role="th">runtime</th>
<th data-quarto-table-cell-role="th">spoken_languages</th>
<th data-quarto-table-cell-role="th">status</th>
<th data-quarto-table-cell-role="th">tagline</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">vote_average</th>
<th data-quarto-table-cell-role="th">vote_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>237000000</td>
<td>[{"id": 28, "name": "Action"}, {"id": 12, "nam...</td>
<td>http://www.avatarmovie.com/</td>
<td>19995</td>
<td>[{"id": 1463, "name": "culture clash"}, {"id":...</td>
<td>en</td>
<td>Avatar</td>
<td>In the 22nd century, a paraplegic Marine is di...</td>
<td>150.437577</td>
<td>[{"name": "Ingenious Film Partners", "id": 289...</td>
<td>[{"iso_3166_1": "US", "name": "United States o...</td>
<td>2009-12-10</td>
<td>2787965087</td>
<td>162.0</td>
<td>[{"iso_639_1": "en", "name": "English"}, {"iso...</td>
<td>Released</td>
<td>Enter the World of Pandora.</td>
<td>Avatar</td>
<td>7.2</td>
<td>11800</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>300000000</td>
<td>[{"id": 12, "name": "Adventure"}, {"id": 14, "...</td>
<td>http://disney.go.com/disneypictures/pirates/</td>
<td>285</td>
<td>[{"id": 270, "name": "ocean"}, {"id": 726, "na...</td>
<td>en</td>
<td>Pirates of the Caribbean: At World's End</td>
<td>Captain Barbossa, long believed to be dead, ha...</td>
<td>139.082615</td>
<td>[{"name": "Walt Disney Pictures", "id": 2}, {"...</td>
<td>[{"iso_3166_1": "US", "name": "United States o...</td>
<td>2007-05-19</td>
<td>961000000</td>
<td>169.0</td>
<td>[{"iso_639_1": "en", "name": "English"}]</td>
<td>Released</td>
<td>At the end of the world, the adventure begins.</td>
<td>Pirates of the Caribbean: At World's End</td>
<td>6.9</td>
<td>4500</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>245000000</td>
<td>[{"id": 28, "name": "Action"}, {"id": 12, "nam...</td>
<td>http://www.sonypictures.com/movies/spectre/</td>
<td>206647</td>
<td>[{"id": 470, "name": "spy"}, {"id": 818, "name...</td>
<td>en</td>
<td>Spectre</td>
<td>A cryptic message from Bond’s past sends him o...</td>
<td>107.376788</td>
<td>[{"name": "Columbia Pictures", "id": 5}, {"nam...</td>
<td>[{"iso_3166_1": "GB", "name": "United Kingdom"...</td>
<td>2015-10-26</td>
<td>880674609</td>
<td>148.0</td>
<td>[{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...</td>
<td>Released</td>
<td>A Plan No One Escapes</td>
<td>Spectre</td>
<td>6.3</td>
<td>4466</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="movies-credit" class="level3">
<h3 class="anchored" data-anchor-id="movies-credit">Movies Credit</h3>
<div id="e51f1d6b" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>movies_credit_df <span class="op">=</span> pd.read_csv(<span class="st">'data/tmdb_5000_credits.csv'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>movies_credit_df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>(4803, 4)</code></pre>
</div>
</div>
<div id="bf2da81a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>movies_credit_df.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">movie_id</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">cast</th>
<th data-quarto-table-cell-role="th">crew</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>19995</td>
<td>Avatar</td>
<td>[{"cast_id": 242, "character": "Jake Sully", "...</td>
<td>[{"credit_id": "52fe48009251416c750aca23", "de...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>285</td>
<td>Pirates of the Caribbean: At World's End</td>
<td>[{"cast_id": 4, "character": "Captain Jack Spa...</td>
<td>[{"credit_id": "52fe4232c3a36847f800b579", "de...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>206647</td>
<td>Spectre</td>
<td>[{"cast_id": 1, "character": "James Bond", "cr...</td>
<td>[{"credit_id": "54805967c3a36829b5002c41", "de...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
</section>
<section id="data-preprocessing" class="level1">
<h1>Data Preprocessing</h1>
<div id="fb2d45d4" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>movies_metadata_df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status                4803 non-null   object 
 16  tagline               3959 non-null   object 
 17  title                 4803 non-null   object 
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64  
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB</code></pre>
</div>
</div>
<div id="5e5b1664" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>movies_credit_df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   movie_id  4803 non-null   int64 
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB</code></pre>
</div>
</div>
<section id="combining-both-tables" class="level3">
<h3 class="anchored" data-anchor-id="combining-both-tables">Combining both tables</h3>
<div id="3c98046b" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>movies_df <span class="op">=</span> movies_metadata_df.merge(movies_credit_df.drop(<span class="st">'title'</span>,axis<span class="op">=</span><span class="dv">1</span>),left_on<span class="op">=</span><span class="st">'id'</span>,right_on<span class="op">=</span><span class="st">'movie_id'</span>, how<span class="op">=</span><span class="st">'left'</span>).drop(<span class="st">'movie_id'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="handling-missing-value" class="level2">
<h2 class="anchored" data-anchor-id="handling-missing-value">Handling missing value</h2>
<p>As can be seen in the previous chunk of code, there are some columns with missing values. Generally, we need to handle these missing values. In this case, we are lucky because most of the missing values are not directly related to the content of the movie. For example, the homepage is unlikely to be a significant factor when recommending a movie.</p>
<p>On the other hand, the overview column contains a summary of the movie’s plot, which is crucial for our recommendation system. Therefore, we need to handle missing values in this column carefully.</p>
<p>For now, we will ignore missing values in columns that do not directly impact the movie content and drop rows with missing values in crucial columns like overview.</p>
<p>Although tagline can contains information crucial for the content, we choose not to drop rows with missing values in the tagline column. The tagline is a more condensed version of the information in the overview, meaning its information is already covered by the overview. Therefore, the absence of a tagline does not significantly impact our ability to recommend movies based on their content. Additionally not all movie have a tagline.</p>
<div id="5a362e2c" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>movies_df <span class="op">=</span> movies_df[<span class="op">~</span>movies_df[<span class="st">'overview'</span>].isna()].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="8248ce14" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>movies_df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4800 non-null   int64  
 1   genres                4800 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4800 non-null   int64  
 4   keywords              4800 non-null   object 
 5   original_language     4800 non-null   object 
 6   original_title        4800 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4800 non-null   float64
 9   production_companies  4800 non-null   object 
 10  production_countries  4800 non-null   object 
 11  release_date          4799 non-null   object 
 12  revenue               4800 non-null   int64  
 13  runtime               4800 non-null   float64
 14  spoken_languages      4800 non-null   object 
 15  status                4800 non-null   object 
 16  tagline               3959 non-null   object 
 17  title                 4800 non-null   object 
 18  vote_average          4800 non-null   float64
 19  vote_count            4800 non-null   int64  
 20  cast                  4800 non-null   object 
 21  crew                  4800 non-null   object 
dtypes: float64(3), int64(4), object(15)
memory usage: 825.1+ KB</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<p>Since we have a content-based recommender system in mind, we will explore the data that contains information about the content of the movie. Imagine that your friend comes to you and says, “I’ve just watched The Dark Knight and I love it. Do you know any other movies like that?” There are several factors you can consider to give your friend recommendations:</p>
<ol type="1">
<li><p><strong>The Genre</strong>. Maybe your friend likes action-packed movies or superhero movies. Considering this, you can recommend other action or superhero movies.</p></li>
<li><p><strong>Keywords of the Movie</strong>. This movie might have some keywords attached to it, like DC Comics, superhero, Batman. Considering this, you can recommend not only random superhero movies but something like Superman or Wonder Woman that share the same keywords.</p></li>
<li><p><strong>The Plot</strong>. Maybe your friend is interested in movies with similar plots. A movie where the hero has to save a city from a terrorist attack, for example.</p></li>
<li><p><strong>The Director</strong>. Each movie director has their own style. Maybe your friend is more interested in the style of Christopher Nolan.</p></li>
</ol>
<p>Considering all these factors and many others is the key to making a reliable recommender system.</p>
<section id="exploring-genre" class="level2">
<h2 class="anchored" data-anchor-id="exploring-genre">Exploring Genre</h2>
<section id="how-many-genre-a-movie-have" class="level3">
<h3 class="anchored" data-anchor-id="how-many-genre-a-movie-have">How many Genre a movie have?</h3>
<div id="25282188" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'genres'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(json.loads(x))).describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>count    4800.000000
mean        2.532708
std         1.120651
min         0.000000
25%         2.000000
50%         2.000000
75%         3.000000
max         7.000000
Name: genres, dtype: float64</code></pre>
</div>
</div>
<div id="68cdd9f5" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'genres'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(json.loads(x))).value_counts().sort_index().plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-13-output-1.png" width="583" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As can be seen in the description and the plot, a movie can have a range of 0-7 genres. A movie with 0 genres can be considered as a movie for which we don’t know the genre. From the visualization, we can see that most movies have 2 to 3 genres associated with them.</p>
</section>
<section id="genre-distribution" class="level3">
<h3 class="anchored" data-anchor-id="genre-distribution">Genre Distribution</h3>
<div id="536e47f5" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_genre_list(x):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    genre_movie <span class="op">=</span> []</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    jdata <span class="op">=</span> json.loads(x)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> jdata:</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        genre_movie.append(d[<span class="st">'name'</span>])</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> genre_movie</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>genre_series <span class="op">=</span> []</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, r <span class="kw">in</span> movies_df.iterrows():</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    genre_series <span class="op">+=</span> create_genre_list(r[<span class="st">'genres'</span>])</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>genre_series <span class="op">=</span> pd.Series(genre_series)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cd87284e" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>genre_series.value_counts().plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-15-output-1.png" width="583" height="497" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="9c6bd18f" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(genre_series.value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>20</code></pre>
</div>
</div>
<p>We can see there are 20 genres recorded in total. From these 20 genres, the most common one is drama. However, keep in mind that what makes a movie unique is not just a single genre but combinations of genres. For example, an Action-Comedy movie will have a very different tone from an Action-Mystery movie. Therefore, it is important to maintain this connection later when we create our recommender system.</p>
</section>
</section>
<section id="exploring-keywords" class="level2">
<h2 class="anchored" data-anchor-id="exploring-keywords">Exploring Keywords</h2>
<section id="numbers-of-keywords-in-a-movie" class="level3">
<h3 class="anchored" data-anchor-id="numbers-of-keywords-in-a-movie">Numbers of Keywords in a movie</h3>
<div id="f6aaf046" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'keywords'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(json.loads(x))).describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>count    4800.000000
mean        7.538750
std         6.280662
min         0.000000
25%         3.000000
50%         6.000000
75%        11.000000
max        97.000000
Name: keywords, dtype: float64</code></pre>
</div>
</div>
<div id="071a4d58" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'keywords'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(json.loads(x))).value_counts().sort_index().plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-18-output-1.png" width="575" height="433" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Unlike genres, a movie can have a lot more keywords associated with it. In our database, it can range up to 97 keywords, with a median of 6. This means half of the movies have at least 6 keywords attached to them.</p>
</section>
</section>
<section id="how-many-keywords-there-are" class="level2">
<h2 class="anchored" data-anchor-id="how-many-keywords-there-are">How many keywords there are</h2>
<div id="53e30259" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>keywords <span class="op">=</span> []</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i,r <span class="kw">in</span> movies_df.iterrows():</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    jdata <span class="op">=</span> json.loads(r[<span class="st">'keywords'</span>])</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> jdata:</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>        keywords.append(d[<span class="st">'name'</span>])</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>keywords <span class="op">=</span> pd.Series(keywords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ecf2f928" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(keywords.unique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>9808</code></pre>
</div>
</div>
<div id="652f490e" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>keywords.value_counts().describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>count    9808.000000
mean        3.689437
std         9.669485
min         1.000000
25%         1.000000
50%         1.000000
75%         3.000000
max       324.000000
Name: count, dtype: float64</code></pre>
</div>
</div>
<p>The total number of keywords available is 9808, however, only a quarter of them appear in at least three different movies. We can keep this in mind, since a keyword that appears only in one or two movies will not provide much information for the recommender system.</p>
</section>
<section id="exploring-overviewthe-plot-description" class="level2">
<h2 class="anchored" data-anchor-id="exploring-overviewthe-plot-description">Exploring Overview/The plot description</h2>
<section id="how-many-words-contained-in-an-overview" class="level3">
<h3 class="anchored" data-anchor-id="how-many-words-contained-in-an-overview">How many words contained in an overview?</h3>
<div id="f0cf8650" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'overview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(x.split())).describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>count    4800.000000
mean       52.157292
std        27.867016
min         0.000000
25%        30.000000
50%        48.000000
75%        67.000000
max       175.000000
Name: overview, dtype: float64</code></pre>
</div>
</div>
<div id="fc87385f" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'overview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(x.split())).hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-23-output-1.png" width="583" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="1b0a57ff" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>movies_df[movies_df[<span class="st">'overview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(x.split())) <span class="op">==</span> <span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">budget</th>
<th data-quarto-table-cell-role="th">genres</th>
<th data-quarto-table-cell-role="th">homepage</th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">keywords</th>
<th data-quarto-table-cell-role="th">original_language</th>
<th data-quarto-table-cell-role="th">original_title</th>
<th data-quarto-table-cell-role="th">overview</th>
<th data-quarto-table-cell-role="th">popularity</th>
<th data-quarto-table-cell-role="th">production_companies</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">revenue</th>
<th data-quarto-table-cell-role="th">runtime</th>
<th data-quarto-table-cell-role="th">spoken_languages</th>
<th data-quarto-table-cell-role="th">status</th>
<th data-quarto-table-cell-role="th">tagline</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">vote_average</th>
<th data-quarto-table-cell-role="th">vote_count</th>
<th data-quarto-table-cell-role="th">cast</th>
<th data-quarto-table-cell-role="th">crew</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4399</td>
<td>0</td>
<td>[{"id": 28, "name": "Action"}, {"id": 35, "nam...</td>
<td>NaN</td>
<td>43630</td>
<td>[]</td>
<td>en</td>
<td>The Helix... Loaded</td>
<td></td>
<td>0.0206</td>
<td>[]</td>
<td>...</td>
<td>0</td>
<td>97.0</td>
<td>[{"iso_639_1": "en", "name": "English"}]</td>
<td>Rumored</td>
<td>NaN</td>
<td>The Helix... Loaded</td>
<td>4.8</td>
<td>2</td>
<td>[]</td>
<td>[]</td>
</tr>
</tbody>
</table>

<p>1 rows × 22 columns</p>
</div>
</div>
</div>
<p>As can be seen that the range of overview length is between 0 to 175. Remember that we’ve drop a movie with no overview. It seems like there are still a movie that don’t have an overview. Since it’s only one movie i think it is fair to also drop this movie</p>
<div id="b75046ed" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>movies_df <span class="op">=</span> movies_df[movies_df[<span class="st">'overview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(x.split())) <span class="op">&gt;</span> <span class="dv">0</span>].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exploring-director" class="level2">
<h2 class="anchored" data-anchor-id="exploring-director">Exploring Director</h2>
<section id="extracting-director-from-the-crew" class="level3">
<h3 class="anchored" data-anchor-id="extracting-director-from-the-crew">Extracting Director from the Crew</h3>
<div id="afae3e28" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> return_director(x):</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    jdata <span class="op">=</span> json.loads(x)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> jdata:</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> d[<span class="st">'job'</span>] <span class="op">==</span> <span class="st">'Director'</span>:</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> d[<span class="st">'name'</span>]</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">''</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ffb4abb1" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'crew'</span>].<span class="bu">apply</span>(return_director).value_counts().describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>count    2347.000000
mean        2.044738
std         2.173457
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        29.000000
Name: count, dtype: float64</code></pre>
</div>
</div>
<div id="d43884c4" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'crew'</span>].<span class="bu">apply</span>(return_director).value_counts()[:<span class="dv">20</span>].plot.bar()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-28-output-1.png" width="566" height="555" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="1c19ea88" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'director'</span>] <span class="op">=</span> movies_df[<span class="st">'crew'</span>].<span class="bu">apply</span>(return_director)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are 2346 director recorded in the data, however the majority of them only have one movie directed by them. With the same logic as keywords, we need to keep in mind that the director with only few movies will not enrich our recommender system</p>
</section>
</section>
</section>
<section id="feature-engineering" class="level1">
<h1>Feature Engineering</h1>
<section id="considering-ranking-and-scoring" class="level2">
<h2 class="anchored" data-anchor-id="considering-ranking-and-scoring">Considering Ranking and Scoring</h2>
<p>When you recommend something to someone, you usually rank options based on how well they match what the person likes. In recommender systems, we do the same by calculating a score for each item. This score tells us how relevant each item is to the user’s interests, and we use these scores to rank the items.</p>
<p>In a recommender system, feature engineering is all about transforming raw data into something meaningful that can be used to make recommendations. Considering scoring in recommender systems, we need to transform all the content we have into something that can be quantified. In other words, we have to extract the features into vectors that we can calculate the similarities.</p>
</section>
<section id="genres" class="level2">
<h2 class="anchored" data-anchor-id="genres">Genres</h2>
<p>For our genres, we want to make a vector representation that considers that a movie can have more than one genre. Since there are only 20 genres available, it is reasonable for us to use a binary vector.</p>
<p>For example, if there are three genres only: Action, Drama, and Comedy: * A movie with Action-Drama genres will be represented with 1 1 0. * A movie with Drama-Comedy genres will be represented with 0 1 1.</p>
<div id="da0c3252" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> FunctionTransformer</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> CountVectorizer</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> TfidfVectorizer</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> extract_genre(X):</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    genre_matrix <span class="op">=</span> []</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> X:</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>        row_genres <span class="op">=</span> []</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>        jdata <span class="op">=</span> json.loads(d)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> jdata:</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>            row_genres.append(j[<span class="st">'name'</span>])</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>        genre_matrix.append(row_genres)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> genre_matrix</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>genre_extractor <span class="op">=</span> FunctionTransformer(extract_genre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="15520830" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>genre_vectorizer <span class="op">=</span> CountVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: x, binary<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>genre_matrix <span class="op">=</span> genre_vectorizer.fit_transform(genre_extractor.fit_transform(movies_df[<span class="st">'genres'</span>])).toarray()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="65d72c3a" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>genre_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])</code></pre>
</div>
</div>
</section>
<section id="keywords" class="level2">
<h2 class="anchored" data-anchor-id="keywords">Keywords</h2>
<p>We’re using TF-IDF (Term Frequency-Inverse Document Frequency) to convert keywords into vectors. TF-IDF helps capture the importance of each keyword by balancing how often a keyword appears in a movie against how common it is across all movies. This way, unique keywords for specific movies get more weight, while common ones get less.</p>
<p>Since we know that most keywords appear only once or twice, we won’t need to map those keywords to the vector. This can reduce our dimensionality significantly without losing much information. For now, we will map only keywords that appear at least 5 times.</p>
<div id="d074481c" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> extract_keywords(X):</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>    keywords_matrix <span class="op">=</span> []</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> X:</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>        row_keywords <span class="op">=</span> []</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>        jdata <span class="op">=</span> json.loads(d)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> jdata:</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>            row_keywords.append(j[<span class="st">'name'</span>])</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>        keywords_matrix.append(row_keywords)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> keywords_matrix</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>keywords_extractor <span class="op">=</span> FunctionTransformer(extract_keywords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="31cb3390" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>keywords_vectorizer <span class="op">=</span> TfidfVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: x, min_df<span class="op">=</span><span class="dv">5</span>, binary<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>keywords_matrix <span class="op">=</span> keywords_vectorizer.fit_transform(keywords_extractor.fit_transform(movies_df[<span class="st">'keywords'</span>])).toarray()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="8e481988" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>keywords_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])</code></pre>
</div>
</div>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>For plot overviews, we will use Sentence-BERT (SBERT) to create embeddings. Sentence Transformers, based on the SBERT architecture, allow us to convert text into high-dimensional vectors that capture the semantic meaning of the text.</p>
<p>Unlike simple TF-IDF, SBERT captures the deeper semantic meaning of the text, understanding the context and relationships between words. SBERT is particularly effective for longer texts like plot overviews, providing a more nuanced representation than TF-IDF. Using SBERT embeddings for plot overviews helps us create rich, meaningful representations of the movie plots, enhancing the quality of our recommendations.</p>
<div id="4db64dc7" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.base <span class="im">import</span> BaseEstimator, TransformerMixin</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sentence_transformers <span class="im">import</span> SentenceTransformer</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SbertTransformer(BaseEstimator, TransformerMixin):</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, model_name<span class="op">=</span><span class="st">"all-MiniLM-L6-v2"</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.model_name <span class="op">=</span>model_name</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.model <span class="op">=</span> SentenceTransformer(model_name)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> fit(<span class="va">self</span>, X, y<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> transform(<span class="va">self</span>, X):</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.model.encode(X.<span class="bu">str</span>.lower())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/homebrew/Caskroom/miniforge/base/envs/forecasting/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning:

Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
</code></pre>
</div>
</div>
<div id="3cc9db1c" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>overview_embedder <span class="op">=</span> SbertTransformer() <span class="co"># Using small model</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>overview_embeddings <span class="op">=</span> overview_embedder.fit_transform(movies_df[<span class="st">'overview'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="3ad9be7b" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>overview_embeddings.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>(4799, 384)</code></pre>
</div>
</div>
</section>
<section id="director" class="level2">
<h2 class="anchored" data-anchor-id="director">Director</h2>
<p>We can use similar logic as keywords and genres to vectorize director information. Since director with a few movie wont help us much in term of recommendation, we will use only director with more than 4 movie to vectorize. Due to the fact a movie can only have one director we will be usinng binary representation instead of tfidf</p>
<div id="bcd8f626" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>movies_df[<span class="st">'director'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4          Andrew Stanton
              ...        
4794     Robert Rodriguez
4795         Edward Burns
4796          Scott Smith
4797          Daniel Hsia
4798     Brian Herzlinger
Name: director, Length: 4799, dtype: object</code></pre>
</div>
</div>
<div id="3ed7be3d" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>director_vectorizer <span class="op">=</span> CountVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: [x] <span class="cf">if</span> x <span class="op">!=</span> <span class="st">''</span> <span class="cf">else</span> [], binary<span class="op">=</span><span class="va">True</span>, min_df<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>director_matrix <span class="op">=</span> director_vectorizer.fit_transform(movies_df[<span class="st">'director'</span>]).toarray()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="b3b3dab6" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>director_matrix.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>(4799, 211)</code></pre>
</div>
</div>
</section>
<section id="putting-it-together" class="level2">
<h2 class="anchored" data-anchor-id="putting-it-together">Putting it Together</h2>
<div id="16ce3ffc" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="creating-pipeline-for-feature-extraction" class="level3">
<h3 class="anchored" data-anchor-id="creating-pipeline-for-feature-extraction">Creating Pipeline for Feature Extraction</h3>
<div id="8c6c6b85" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pipeline for Genre Feature Extraction</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>genre_pipeline <span class="op">=</span> Pipeline([</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'genre_extractor'</span>, FunctionTransformer(extract_genre)),</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'genre_vectorizer'</span>, CountVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: x, binary<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pipeline for Keywords Feature Extraction</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>keywords_pipeline <span class="op">=</span> Pipeline([</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'keywords_extractor'</span>, FunctionTransformer(extract_keywords)),</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'keywords_vectorizer'</span>, TfidfVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: x, min_df<span class="op">=</span><span class="dv">5</span>, binary<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="joining-all-feature" class="level3">
<h3 class="anchored" data-anchor-id="joining-all-feature">Joining all feature</h3>
<div id="3c482fac" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>feature_extractor <span class="op">=</span> ColumnTransformer([</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'genres_pipeline'</span>, genre_pipeline, <span class="st">"genres"</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'keywords_pipeline'</span>, keywords_pipeline, <span class="st">"keywords"</span>),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'overview_pipeline'</span>, SbertTransformer(), <span class="st">"overview"</span>),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'director_pipeline'</span>, CountVectorizer(analyzer<span class="op">=</span> <span class="kw">lambda</span> x: [x] <span class="cf">if</span> x <span class="op">!=</span> <span class="st">''</span> <span class="cf">else</span> [], binary<span class="op">=</span><span class="va">True</span>, min_df<span class="op">=</span><span class="dv">5</span>), <span class="st">"director"</span>)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="2f97f2c6" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>feature_matrix <span class="op">=</span> feature_extractor.fit_transform(movies_df).toarray()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="08d1e9d9" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>feature_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="build-a-recommender-system" class="level1">
<h1>Build a Recommender System</h1>
<p>Remember that I mentioned about scoring and ranking. Now in order to actually recommend a movie, we need to score their similirarity to each other. There are several ways to do this, but the most common one for data involving text is <strong>Cosine Similarity</strong>.</p>
<p>Cosine similarity measures how similar two items are by looking at the angle between their vectors. Think of it as comparing the direction of two arrows, regardless of their length. If the arrows point in the same direction, they’re similar. In addition to that, It’s quick and can handle lots of data without much fuss.</p>
<div id="0753f83b" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>movies_list <span class="op">=</span> movies_df[[<span class="st">'id'</span>,<span class="st">'original_title'</span>]].copy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="f32fcdda" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>similarity_matrix <span class="op">=</span> cosine_similarity(feature_matrix, feature_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="733a6e22" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> find_similar_movie_using_similarity(movie_id: <span class="bu">int</span>):</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>    indx <span class="op">=</span> movies_list[movies_list[<span class="st">'id'</span>] <span class="op">==</span> movie_id].index.tolist()[<span class="dv">0</span>]</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    top_similar <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">list</span>(<span class="bu">enumerate</span>(similarity_matrix[indx])), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)[<span class="dv">1</span>:<span class="dv">11</span>]</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    recommended_movies <span class="op">=</span> movies_list.iloc[[t[<span class="dv">0</span>] <span class="cf">for</span> t <span class="kw">in</span> top_similar]].copy()</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    recommended_movies[<span class="st">'similarity_score'</span>] <span class="op">=</span> [t[<span class="dv">1</span>] <span class="cf">for</span> t <span class="kw">in</span> top_similar]</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> recommended_movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="running-the-recommender-function" class="level2">
<h2 class="anchored" data-anchor-id="running-the-recommender-function">Running the Recommender Function</h2>
<p>Now let’s use this recommender system to recommend movies to our friend who just watched Batman Begins.</p>
<div id="c91f5d73" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>movies_list[movies_list[<span class="st">'original_title'</span>].<span class="bu">str</span>.contains(<span class="st">'Batman'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">original_title</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>209112</td>
<td>Batman v Superman: Dawn of Justice</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">119</td>
<td>272</td>
<td>Batman Begins</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">210</td>
<td>415</td>
<td>Batman &amp; Robin</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">299</td>
<td>414</td>
<td>Batman Forever</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">428</td>
<td>364</td>
<td>Batman Returns</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1359</td>
<td>268</td>
<td>Batman</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3853</td>
<td>142061</td>
<td>Batman: The Dark Knight Returns, Part 2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4265</td>
<td>2661</td>
<td>Batman</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="7ca67f78" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>batman_begins_id <span class="op">=</span> <span class="dv">272</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="9945521e" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>find_similar_movie_using_similarity(batman_begins_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">original_title</th>
<th data-quarto-table-cell-role="th">similarity_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">65</td>
<td>155</td>
<td>The Dark Knight</td>
<td>0.792444</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>49026</td>
<td>The Dark Knight Rises</td>
<td>0.770914</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3325</td>
<td>312113</td>
<td>Black November</td>
<td>0.663642</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1742</td>
<td>254473</td>
<td>Brick Mansions</td>
<td>0.659899</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4634</td>
<td>378237</td>
<td>Amidst the Devil's Wings</td>
<td>0.630629</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3358</td>
<td>22314</td>
<td>In Too Deep</td>
<td>0.625375</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1486</td>
<td>7220</td>
<td>The Punisher</td>
<td>0.624695</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3818</td>
<td>34769</td>
<td>Defendor</td>
<td>0.622456</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3827</td>
<td>9516</td>
<td>Menace II Society</td>
<td>0.612793</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1661</td>
<td>9989</td>
<td>Antitrust</td>
<td>0.607391</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>As can be seen from our algorithm, when asked to recommend movies like “Batman Begins,” it recommends “The Dark Knight” and “The Dark Knight Rises,” which are sequels to the movie. On top of that, we also see movies with some detective and superhero vibes. This indicates that our content-based recommender system is effectively identifying and recommending movies that share significant characteristics with the user’s input, thus providing relevant and meaningful suggestions.</p>
</section>
</section>
<section id="improving-recomender-system" class="level1">
<h1>Improving Recomender System</h1>
<p>Can we improve this model? Yes. In order to improve a model, we need a strategy to quantify the performance of the model itself. In terms of recommender systems, one common evaluation metric is Precision at K (P@K). Precision at K measures the relevance of the top K recommendations made by the system. It is defined as the proportion of recommended items in the top K set that are relevant.</p>
<p>Unfortunately, our dataset is not ideal for evaluating the recommender system since we don’t have the actual user consumption data. Without knowing what movies users have actually watched and liked, we can’t accurately measure how well our recommendations match user preferences.</p>
<p>That being said, there are several strategies to improve the model: 1. <strong>Give Different Weight to Each Feature:</strong> Currently, we are treating every feature as equally important. Depending on the case, this might not be the most optimal. By adjusting the weights of different features (e.g., giving more importance to plot similarity over genre similarity), we can potentially improve the relevance of our recommendations.</p>
<ol start="2" type="1">
<li><p><strong>Add More Relevant Features:</strong> We can incorporate additional features that are relevant to the content of the movie, such as the cast, the director, or even more granular details like the sound engineer. These additional features can provide a richer context for making recommendations.</p></li>
<li><p><strong>Combine Content-Based Approach with Collaborative Filtering:</strong> Creating a hybrid recommender system by combining content-based filtering with collaborative filtering can leverage the strengths of both approaches. While content-based filtering focuses on item attributes, collaborative filtering leverages user behavior and preferences. This combination can result in more accurate and personalized recommendations.</p></li>
</ol>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Building a content-based recommender system using the TMDB 5000 dataset has allowed us to explore various aspects of feature engineering and similarity scoring. By converting genres into binary vectors, using TF-IDF for keywords, and employing SBERT for plot overviews, we created a comprehensive model capable of providing relevant movie recommendations.</p>
<p>Our model, when asked to recommend movies like “Batman Begins,” successfully suggested sequels like “The Dark Knight” and “The Dark Knight Rises,” as well as other movies with similar detective and superhero vibes. This demonstrates the effectiveness of our content-based approach in capturing the nuances of movie content.</p>
<p>However, there is always room for improvement. Precision at K (P@K) is a common metric for evaluating recommender systems, but our dataset lacks actual user consumption data, which limits our ability to accurately measure performance.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/yjhouma\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>